// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $ChatbotModal from "./islands/ChatbotModal.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $PetModal from "./islands/PetModal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/ChatbotModal.tsx": $ChatbotModal,
    "./islands/Modal.tsx": $Modal,
    "./islands/PetModal.tsx": $PetModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
